id: ID2B77AAB
legacy_id: P000303
ocr_import_info:
  bdrc_scan_id: W1KG12025
  source: bdrc
  ocr_info:
    timestamp: '2020-03-10T19:07:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:14:19.570737+00:00'
last_modified: 2022-08-31 11:14:34.755474
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12025
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12025
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་སྤྱི་དོན་དང་གཞུང་འགྲེལ།
  author: དྷཱརྨ་ཀིརྟི་ཀུན་བཟང་བསོད་ནམས།
statistics:
  ocr_word_mean_confidence_index: 0.5474510575843927
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I1KG12058:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12058
      total_pages: 450
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12058.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5474510575843927
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
