id: ID2B77AAB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T19:11:00+00:00'
last_modified: '2022-06-15T15:18:23.051762+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12025
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་སྤྱི་དོན་དང་གཞུང་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E695:
      image_group_id: I1KG12058
      title: Volume 1 of spyod 'jug shes rab le'u'i spyi don dang gzhung 'grel/
      total_pages: 450
      order: 1
      base_file: E695.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
